apiVersion: v1
kind: Namespace
metadata:
  name: foo
  labels:
    environment-id: env_3eb1417e-3b01-443f-b61c-84ad0f14bab8
    project-id: project_321ee76a-cbcd-40f6-bc24-f0e7285a572c
    project-name: Port505
    environment-name: dev
    organization-id: org_01b50229-db34-43d4-8f3e-d1aeb683d900
